### ISSUE TITLE
Currying template

### ISSUE THREAD

**Issue by tylerjw** [tylerjw/monad#7]
### Need

_In order to_ call functions that have multiple inputs in a monadic way
_As a_ user
_I want to_ have nice syntax for curing a function

### Scenario

**Scenario:** fp should provide a curry function
**GIVEN** A function with multiple inputs
**WHEN** I curry it with this new Curried type
**THEN** I should have a function that can be called with a single argument.

Reference: https://en.wikipedia.org/wiki/Currying

### Tasks

- [ ] _What:_ Search for and read existing implementations of Currying in C++
  _Why:_ To understand how it might be implemented and what is difficult about Currying
  _Impact:_ Implementing Currying should be more straightforward

- [ ] _What:_ Write a test and example to show how the interface will work
  _Why:_ To understand what a nice interface will look like
  _Impact:_ Currying interface will be better understood

- [ ] _What:_ Create the type to curry functions
  _Why:_ To have this feature
  _Impact:_ Test will pass

**Comment by tylerjw** [comment]
https://compiler-explorer.com/z/WYKMT4eY6

**Comment by tylerjw** [comment]
Pasting here incase the compiler-explorer link ever goes dead:

```c++
#include <iostream>

template <typename Callable, typename... Params>
auto curry(Callable f, Params... ps)
{
  if constexpr (requires { f(ps...); }) {
    return f(ps...);
  } else {
    return [f, ps...] (auto... qs)
    {
      return curry(f, ps..., qs...);
    };
  }
}

int func1(int x, int y)
{
  return x + y;
}

int main()
{
  const auto f = curry(func1);
  std::cout << f(1)(2) << '\n';
  return 0;
}
```

**Comment by tylerjw** [comment]
https://github.com/lefticus/tools/blob/main/include/lefticus/tools/curry.hpp
